// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListActiveUsers(ctx context.Context, arg ListActiveUsersParams) ([]User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
