// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: role.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listRolesByUserId = `-- name: ListRolesByUserId :many
SELECT r.name
FROM user_role ur
JOIN role r ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) ListRolesByUserId(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
