# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: mangtoon
          POSTGRES_USER: root
          POSTGRES_PASSWORD: dev
#        comment this out, since it fails the job
#        options: >-
#          --health-cmd pd_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install goose
        run: curl -fsSL https://raw.githubusercontent.com/pressly/goose/master/install.sh | sh -s v3.20.0

      - name: Run goose's db migrations
        run: make db-migrate-up

      - name: Test
        run: make test